spring:
  sql:
    init:
      mode: never
  application:
    name: cathay-test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

multi:
  datasource:
    properties:
      db1:
        url: jdbc:h2:mem:db1
        driverClassName: org.h2.Driver
        username: sa
        password:
      db2:
        url: jdbc:h2:mem:db2
        driverClassName: org.h2.Driver
        username: sa
        password: